// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5CLcWUZoYo3MOK43TUZrnqi9bS2ICX6E',
    appId: '1:574955679563:web:d966e0e11cd57444fa02ce',
    messagingSenderId: '574955679563',
    projectId: 'whatsapp-backend-f4d87',
    authDomain: 'whatsapp-backend-f4d87.firebaseapp.com',
    storageBucket: 'whatsapp-backend-f4d87.appspot.com',
    measurementId: 'G-GV24MSHWJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lbVr8JHGVmCWL_Mzg81nTN-fys0JBN0',
    appId: '1:574955679563:android:aed00bb1624d3e8efa02ce',
    messagingSenderId: '574955679563',
    projectId: 'whatsapp-backend-f4d87',
    storageBucket: 'whatsapp-backend-f4d87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDezV5CddYoEy2WGlF7K8u6Ndz6DQdmwLo',
    appId: '1:574955679563:ios:5cea118c11f3c7dcfa02ce',
    messagingSenderId: '574955679563',
    projectId: 'whatsapp-backend-f4d87',
    storageBucket: 'whatsapp-backend-f4d87.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDezV5CddYoEy2WGlF7K8u6Ndz6DQdmwLo',
    appId: '1:574955679563:ios:5cea118c11f3c7dcfa02ce',
    messagingSenderId: '574955679563',
    projectId: 'whatsapp-backend-f4d87',
    storageBucket: 'whatsapp-backend-f4d87.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
